<h1>Updating Our Terms and Policies: Helping You Understand How Facebook Works and How to Control Your Information</h1>

<img src="img/facebookTerms-sm.jpg" title="you're in control, apparently."/>

<br/>
Over the past year, we’ve introduced new features and controls to help you get more out of Facebook, and listened to people who have asked us to better explain how we get and use information.
Now, with Privacy Basics, you'll get tips and a how-to guide for taking charge of your experience on Facebook. We're also updating our terms, data policy and cookies policy to reflect new features we've been working on and to make them easy to understand.
These updates take effect on January 1, 2015. As always, we welcome your feedback about our policies.
<br/><br/>
<strong>
Privacy Basics<br/>
</strong>
Privacy Basics offers interactive guides to answer the most commonly asked questions about how you can control your information on Facebook. For example, you can learn about untagging, unfriending, blocking and how to choose an audience for each of your posts. This information is available in 36 languages.
Along with our privacy checkup, reminder for people posting publicly and simplified audience selectors, Privacy Basics is the latest step we've taken to help you make sure you're sharing with the people you want.
<br/><br/>
<strong>
Helping you get more out of Facebook<br/>
</strong>
Every day, people use our apps and services to connect with the people, places and things they care about. The updates to our policies reflect the new products we've been working on to improve your Facebook experience. They also explain how our services work in a way that's easier to understand. Here are some highlights:<br/>
Discover what's going on around you: We’re updating our policies to explain how we get location information depending on the features you decide to use. Millions of people check into their favorite places and use optional features like Nearby Friends (currently only available in some regions). We're working on ways to show you the most relevant information based on where you are and what your friends are up to. For example, in the future, if you decide to share where you are, you might see menus from restaurants nearby or updates from friends in the area.<br/>
Make purchases more convenient: In some regions, we're testing a Buy button that helps people discover and purchase products without leaving Facebook. We're also working on new ways to make transactions even more convenient.<br/>
Find information about privacy on Facebook at the moment you need it: To make them more accessible, we moved tips and suggestions to Privacy Basics. Our data policy is shorter and clearer, making it easier to read.<br/>
Understand how we use the information we receive: For example, understanding battery and signal strength helps make sure our apps work well on your device. We ask for permission to use your phone's location when we offer optional features like check-ins or adding your location to posts.<br/>
Get to know how the family of Facebook companies and apps work together: Over the past few years, Facebook has grown and we want to make sure you know about our family of companies, apps and services. We use the information we collect to improve your experience. For example, if you're locked out of your Instagram account, you can use your Facebook information to recover your password. Nothing in our updates changes the commitments that Instagram, WhatsApp and other companies have made to protect your information and your privacy.<br/>
Your information and advertising: People sometimes ask how their information is shared with advertisers. Nothing is changing with these updates—we help advertisers reach people with relevant ads without telling them who you are. Learn more about ads and how you can control the ads you see.
<br/>
<br/>
<strong>
Giving you more control over ads</strong>

We've heard from some of you that it can be difficult to control the types of ads you see if you use multiple devices and browsers. In the past, if you opted out of certain kinds of advertising on your laptop, that choice may not have been applied for ads on your phone. We know that many people use more than one phone, tablet or browser to access Facebook, so it should be easy for you to make a single choice that applies across all of your devices.<br/>
That's why Facebook respects the choices you make about the ads you see, across every device. You can opt out of seeing ads on Facebook based on the apps and sites you use through the Digital Advertising Alliance. You can also opt out using controls on iOS and Android. When you tell us you don't want to see these types of ads, your decision automatically applies to every device you use to access Facebook. Also, we're now making ad preferences available in additional countries, beginning with Australia, Canada, France, Germany, Ireland and the UK.
We hope these updates improve your experience. Protecting people's information and providing meaningful privacy controls are at the core of everything we do, and we believe these announcements are an important step.